spring.application.name=job-tracking

# PostgreSQL connection
spring.datasource.url=jdbc:postgresql://localhost:5432/jobtracking
spring.datasource.username=root
spring.datasource.password=admin

# Initialize database from schema.sql
spring.sql.init.mode=always
