spring.application.name=job-tracking

# PostgreSQL connection ? ?????????? ?????????? ?????????
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/jobtracking}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:admin}

# Initialize database from schema.sql
spring.sql.init.mode=always
